name: Release Compiler
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pax
            os_suffix: pax-linux-x64
            # URL Linux
            mdbook_url: https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz
          - os: macos-latest
            artifact_name: pax
            os_suffix: pax-macos-x64
            # URL macOS (Darwin)
            mdbook_url: https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-apple-darwin.tar.gz
          - os: windows-latest
            artifact_name: pax.exe
            os_suffix: pax-windows-x64
            # URL Windows
            mdbook_url: https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-pc-windows-msvc.zip

    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          curl -sSL ${{ matrix.mdbook_url }} | tar -xz
          chmod +x mdbook

      - name: Install mdBook (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -sSL ${{ matrix.mdbook_url }} -o mdbook.zip
          tar -xf mdbook.zip

      - name: Build Documentation
        run: |
          ${{ runner.os == 'Windows' && './mdbook.exe' || './mdbook' }} build docs

      - name: Build Pax (Rust)
        run: cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: pax-${{ github.ref_name }}-${{ matrix.os_suffix }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          tag: ${{ github.ref }}
          overwrite: true